### PR TITLE
First Attempt

### PR DESCRIPTION
**Pull request by Chummel**

### CODE REVIEW

**Comment by halfaro1** [comment]
@Chummel great start. I believe you'll have a little more luck if you use the os.join function that was described in the textbook. Remember that although you may be running your program on one type of OS, the program needs to run on any type of OS.

**Comment by Chummel** [comment]
I've been attempting to run this in the python shell and I get the error message "RESTART: C:\Users\Colin\Desktop\Programming\project-working-with-files\randomQuizGenerator.py" which seems odd to me, also I've attempted to sync the latest week of work yet it's saying that I don't have permission to sync.

**Comment by halfaro1** [comment]
@Chummel not having permission to synch usually means you're trying to synch to my original repository instead of your fork. Make sure you're synching to your fork. Let me know if you need help.

**Comment by halfaro1** [comment]
@Chummel 
Thanks for continuing to work on this project! Unfortunately, I have to grade this project as-is. I am closing out this pull request and entering your grade on Blackboard. Please see your grade there.

**Pull request closed without merging**
