### PR TITLE
#1

### PR DESCRIPTION
**Pull request by nhatnam113**

### CODE REVIEW

**Comment by halfaro1** [comment]
@nhatnam113 it looks like you tried to start another student's submission -- do you need help with this?

**Comment by nhatnam113** [comment]
Hi Professor,
I really need your help on W10 because it was really hard to me. Please help me.
Thank you very much
Nam Nguyen
________________________________

**Comment by halfaro1** [comment]
@nhatnam113 good start, use the os.join function any time that you use a forward slash.

**Comment by halfaro1** [comment]
Closing and reopening the pull request to force the automated check to run...

**Comment by halfaro1** [comment]
@nhatnam113 
Fantastic work :+1:
I'm marking this pull request as closed, and labeling it as `graded` while I finish grading these projects. When I'm done grading all the projects, and your grade should be on Blackboard, I'll change the tag to `grade updated on blackboard`

**Pull request closed without merging**
