### PR TITLE
Elice Greenberg- Week 11

### PR DESCRIPTION
**Pull request by elicegreen**

### CODE REVIEW

**Comment by elicegreen** [comment]
I can not figure out what is wrong with my code

**Comment by halfaro1** [comment]
@elicegreen great start. I believe you'll have a little more luck if you use the os.join function that was described in the textbook. Remember that although you may be running your program on one type of OS, the program needs to run on any type of OS.

**Comment by elicegreen** [comment]
Yes!!! Finally!!! :-D

**Comment by halfaro1** [comment]
@elicegreen great work!

**Pull request closed without merging**
