### PR TITLE
week10

### PR DESCRIPTION
**Pull request by alalta**

### CODE REVIEW

**Comment by halfaro1** [comment]
@alalta great start. However, your code is missing the modification I specified -- you're to create two folders and place the files into those folders. The `os` module should help with this (which I already see you imported).

**Comment by alalta** [comment]
Professor, im still trying to figure out how to create another folder and I cant seem to figure it out.

**Comment by halfaro1** [comment]
@alalta did you check out the working with files chapter?

**Comment by halfaro1** [comment]
@alalta 
Thanks for continuing to work on this project! Unfortunately, I have to grade this project as-is. I am closing out this pull request and entering your grade on Blackboard. Please see your grade there.

**Pull request closed without merging**
