### PR TITLE
Attempt 1

### PR DESCRIPTION
**Pull request by larawillson**

### CODE REVIEW

**Comment by larawillson** [comment]
@halfaro1 Mr. Alfaro, I have tried just about everything I can think of and I can not get the directories to be created. When I run the program in Idle, I get the following errors:

Traceback (most recent call last):
  File "/Users/LaraWillson/Desktop/cop_1000/project-working-with-files/test_randomQuizGen.py", line 4, in <module>
    shutil.rmtree('answers')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 370, in _rmtree_unsafe
    onerror(os.listdir, path, sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 368, in _rmtree_unsafe
    names = os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: 'answers'

Is there anything that you can see that would be causing these problems?

**Comment by BranLWill** [comment]
Yah i'm getting the same error with mine as well.

**Comment by chrispelaez** [comment]
when you run the program does it create the question/answer folders? Are you using the github app or applying the code directly to the github website? Your destination folders look good but their not reflecting in your work. try doing a pull request through the github app. I had a similar problem that was resolved by using the github app verses the actual website.

**Comment by BranLWill** [comment]
yes it does create both folders and i have tried both ways of uploading it to github and it is still giving me the same errors in the travis ci check. It gives this error:

==================================== ERRORS ====================================

____________________ ERROR collecting test_randomQuizGen.py ____________________

test_randomQuizGen.py:4: in <module>

    shutil.rmtree('answers')

../../../virtualenv/python3.5.0/lib/python3.5/shutil.py:465: in rmtree

    onerror(os.lstat, path, sys.exc_info())

../../../virtualenv/python3.5.0/lib/python3.5/shutil.py:463: in rmtree

    orig_st = os.lstat(path)

E   FileNotFoundError: [Errno 2] No such file or directory: 'answers'

=========================== 1 error in 0.05 seconds ============================



________________________________

**Comment by halfaro1** [comment]
Good job, collaborating @larawillson @BranLWill and @chrispelaez 

I believe you'll have a little more luck if you use the os.join function that was described in the textbook. Remember that although you may be running your program on one type of OS, the program needs to run on any type of OS.

**Comment by larawillson** [comment]
@halfaro1 I'm sorry I'm still struggling with this one. I'm thinking that my issue is that my directories are not creating to begin with, but I'm struggling with a way to implement os.join to solve the issue. Should this be used when creating the directory, or when creating the file in the directory? I've tried both, but to no avail :(

**Comment by larawillson** [comment]
@BranLWill I'm not sure if you are still having the same problem or if you were doing what I was doing, but it turns out I was running the test file, not the Quiz Generator file, which is what was causing that error :)

**Comment by halfaro1** [comment]
@larawillson looks like you got it to work - great job!

**Pull request closed without merging**
